name = "swift-utilities"
tools_version = "5.9"
default_localization = "en"

# Platforms

[platforms.iOS]
supported = [ "\"17.0\"" ]

[platforms.macOS]
supported = [ "\"14.0\"" ]

# Services

[services.Analytics.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]
[services.TelemetryDeckAnalytics]
skip_interface = true
services = [ "Analytics", "Bundle", "UserDefaults" ]
dependencies = [ "TelemetryClient" ]

[services.AppInfo]
services = [ "Bundle", "UserDefaults" ]
[services.AppInfo.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.Bundle]
skip_tests = true
[services.Bundle.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.GRDBDatabase]
services = [ "FileManager" ]
[services.GRDBDatabase.interface]
libraries = [ "GRDBDatabase" ]
dependencies = [ "ConcurrencyExtras", "Dependencies", "DependenciesMacros" ]
[services.GRDBDatabase.tests]
libraries = [ "TestUtilities" ]

[services.SentryErrorReporting]
skip_interface = true
skip_tests = true
libraries = [ "ErrorReportingClient" ]
dependencies = [ "Sentry" ]

[services.FeatureFlags]
services = [ "Bundle", "UserDefaults" ]
[services.FeatureFlags.interface]
libraries = [ "FeatureFlags" ]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.FileManager]
[services.FileManager.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.Pasteboard]
[services.Pasteboard.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.StoreReview]
services = [ "AppInfo", "UserDefaults" ]
[services.StoreReview.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.UserDefaults]
[services.UserDefaults.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

# Libraries

[libraries.GRDBDatabase]
dependencies = [ "GRDB" ]

[libraries.Equatable]

[libraries.ErrorReportingClient]
skip_tests = true
dependencies = [ "Dependencies", "DependenciesMacros" ]

[libraries.Extensions]
dependencies = [ "AsyncAlgorithms", "ConcurrencyExtras" ]
[libraries.Extensions.tests]
dependencies = [ "Dependencies" ]

[libraries.FeatureFlags]

[libraries.SwiftUIExtensions]
[libraries.SwiftUIExtensions.tests]
dependencies = [ "SnapshotTesting" ]

[libraries.GRDBDatabaseTestUtilities]
skip_tests = true
dependencies = [ "GRDB" ]

[libraries.TestUtilities]
skip_tests = true

# Dependency Versions

[versionRefs.Dependencies]
from = "1.2.2"

# Dependencies

[dependencies.AsyncAlgorithms]
url = "https://github.com/apple/swift-async-algorithms.git"
from = "1.0.0"

[dependencies.Dependencies]
url = "https://github.com/pointfreeco/swift-dependencies.git"
versionRef = "Dependencies"

[dependencies.DependenciesMacros]
url = "https://github.com/pointfreeco/swift-dependencies.git"
versionRef = "Dependencies"

[dependencies.ConcurrencyExtras]
url = "https://github.com/pointfreeco/swift-concurrency-extras.git"
from = "1.1.0"

[dependencies.GRDB]
url = "https://github.com/groue/GRDB.swift.git"
from = "6.25.0"

[dependencies.Sentry]
url = "https://github.com/getsentry/sentry-cocoa.git"
from = "8.21.0"

[dependencies.SnapshotTesting]
suitable_for_dependents_matching = "\\w+Tests$"
url = "https://github.com/pointfreeco/swift-snapshot-testing.git"
from = "1.16.0"

[dependencies.TelemetryClient]
url = "https://github.com/TelemetryDeck/SwiftClient.git"
from = "1.5.1"
