name = "swift-utilities"
tools_version = "5.9"
default_localization = "en"

# Platforms

[platforms.iOS]
supported = [ "\"17.0\"" ]

[platforms.macOS]
supported = [ "\"14.0\"" ]

# Services

[services.Analytics.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]
[services.TelemetryDeckAnalytics]
skip_interface = true
services = [ "Analytics", "Bundle", "UserDefaults" ]
dependencies = [ "TelemetryClient" ]

[services.Bundle]
skip_tests = true
[services.Bundle.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.SentryErrorReporting]
skip_interface = true
skip_tests = true
libraries = [ "ErrorReportingClient" ]
dependencies = [ "Sentry" ]

[services.FileManager]
[services.FileManager.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.Pasteboard]
[services.Pasteboard.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.UserDefaults]
[services.UserDefaults.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

# Libraries

[libraries.Equatable]

[libraries.ErrorReportingClient]
skip_tests = true
dependencies = [ "Dependencies", "DependenciesMacros" ]

[libraries.Extensions]

[libraries.SwiftUIExtensions]
[libraries.SwiftUIExtensions.tests]
dependencies = [ "SnapshotTesting" ]

[libraries.TestUtilities]
skip_tests = true

# Dependency Versions

[versionRefs.Dependencies]
from = "1.2.2"

# Dependencies

[dependencies.Dependencies]
url = "https://github.com/pointfreeco/swift-dependencies.git"
versionRef = "Dependencies"

[dependencies.DependenciesMacros]
url = "https://github.com/pointfreeco/swift-dependencies.git"
versionRef = "Dependencies"

[dependencies.Sentry]
url = "https://github.com/getsentry/sentry-cocoa.git"
from = "8.21.0"

[dependencies.SnapshotTesting]
suitable_for_dependents_matching = "\\w+Tests$"
url = "https://github.com/pointfreeco/swift-snapshot-testing.git"
from = "1.16.0"

[dependencies.TelemetryClient]
url = "https://github.com/TelemetryDeck/SwiftClient.git"
from = "1.5.1"
