name = "swift-utilities"
tools_version = "6.1"
default_localization = "en"

# Platforms

[platforms.iOS]
supported = [ "\"17.0\"" ]

[platforms.macOS]
supported = [ "\"14.0\"" ]

[platforms.watchOS]
supported = [ "\"9.0\"" ]

# Services

[services.AnalyticsPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]
[services.TelemetryDeckAnalyticsPackage]
skip_interface = true
services = [ "AnalyticsPackage", "BundlePackage", "UserDefaultsPackage" ]
dependencies = [ "TelemetryDeck" ]

[services.AppInfoPackage]
services = [ "BundlePackage", "UserDefaultsPackage" ]
[services.AppInfoPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.BundlePackage]
skip_tests = true
[services.BundlePackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.GRDBDatabasePackage]
[services.GRDBDatabasePackage.interface]
services = [ "FileManagerPackage" ]
libraries = [ "GRDBDatabasePackage" ]
dependencies = [ "ConcurrencyExtras" ]
[services.GRDBDatabasePackage.tests]
libraries = [ "TestUtilitiesPackage" ]

[services.SentryErrorReportingPackage]
skip_interface = true
skip_tests = true
libraries = [ "ErrorReportingClientPackage" ]
dependencies = [ "Sentry" ]

[services.FeatureFlagsPackage]
services = [ "BundlePackage", "UserDefaultsPackage" ]
[services.FeatureFlagsPackage.interface]
libraries = [ "FeatureFlagsPackage" ]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.FileManagerPackage]
[services.FileManagerPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.PasteboardPackage]
[services.PasteboardPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.StoreReviewPackage]
services = [ "AppInfoPackage", "UserDefaultsPackage" ]
[services.StoreReviewPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.UserDefaultsPackage]
[services.UserDefaultsPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

# Libraries

[libraries.GRDBDatabasePackage]
dependencies = [ "GRDB" ]

[libraries.EquatablePackage]

[libraries.ErrorReportingClientPackage]
skip_tests = true
dependencies = [ "Dependencies", "DependenciesMacros" ]

[libraries.ExtensionsPackage]
dependencies = [ "AsyncAlgorithms", "ConcurrencyExtras" ]
[libraries.ExtensionsPackage.tests]
dependencies = [ "Dependencies" ]

[libraries.FeatureFlagsPackage]

[libraries.SwiftUIExtensionsPackage]
[libraries.SwiftUIExtensionsPackage.tests]
dependencies = [ "SnapshotTesting" ]

[libraries.GRDBDatabaseTestUtilitiesPackage]
skip_tests = true
libraries = [ "GRDBDatabasePackage" ]

[libraries.TestUtilitiesPackage]
skip_tests = true

# Dependency Versions

[shared.refs]
AsyncAlgorithms = { url = "https://github.com/apple/swift-async-algorithms.git", from = "1.0.4" }
Dependencies = { url = "https://github.com/pointfreeco/swift-dependencies.git", from = "1.9.2"}
ConcurrencyExtras = { url = "https://github.com/pointfreeco/swift-concurrency-extras.git", from = "1.3.1" }
GRDB = { url = "https://github.com/groue/GRDB.swift.git", from = "7.0.0" }
Sentry = { url = "https://github.com/getsentry/sentry-cocoa.git", from = "8.50.1" }
SnapshotTesting = { url = "https://github.com/pointfreeco/swift-snapshot-testing.git", from = "1.17.7" }
TelemetryDeck = { url = "https://github.com/TelemetryDeck/SwiftSDK.git", from = "2.7.0" }

# Dependencies

[dependencies.AsyncAlgorithms]
dep_ref = "AsyncAlgorithms"
[dependencies.Dependencies]
dep_ref = "Dependencies"
[dependencies.DependenciesMacros]
dep_ref = "Dependencies"
[dependencies.ConcurrencyExtras]
dep_ref = "ConcurrencyExtras"
[dependencies.GRDB]
dep_ref = "GRDB"
[dependencies.Sentry]
dep_ref = "Sentry"
[dependencies.SnapshotTesting]
suitable_for_dependents_matching = "\\w+Tests$"
dep_ref = "SnapshotTesting"
[dependencies.TelemetryDeck]
dep_ref = "TelemetryDeck"
