name = "swift-utilities"
tools_version = "5.10"
default_localization = "en"

# Platforms

[platforms.iOS]
supported = [ "\"17.0\"" ]

[platforms.macOS]
supported = [ "\"14.0\"" ]

[platforms.watchOS]
supported = [ "\"9.0\"" ]

# Configuration
[shared]
swift_settings = [ ".enableExperimentalFeature(\"StrictConcurrency\")" ]

# Services

[services.AnalyticsPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]
[services.TelemetryDeckAnalyticsPackage]
skip_interface = true
services = [ "AnalyticsPackage", "BundlePackage", "UserDefaultsPackage" ]
dependencies = [ "TelemetryDeck" ]

[services.AppInfoPackage]
services = [ "BundlePackage", "UserDefaultsPackage" ]
[services.AppInfoPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.BundlePackage]
skip_tests = true
[services.BundlePackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.GRDBDatabasePackage]
services = [ "FileManagerPackage" ]
[services.GRDBDatabasePackage.interface]
libraries = [ "GRDBDatabasePackage" ]
dependencies = [ "ConcurrencyExtras", "Dependencies", "DependenciesMacros" ]
[services.GRDBDatabasePackage.tests]
libraries = [ "TestUtilitiesPackage" ]

[services.SentryErrorReportingPackage]
skip_interface = true
skip_tests = true
libraries = [ "ErrorReportingClientPackage" ]
dependencies = [ "Sentry" ]

[services.FeatureFlagsPackage]
services = [ "BundlePackage", "UserDefaultsPackage" ]
[services.FeatureFlagsPackage.interface]
libraries = [ "FeatureFlagsPackage" ]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.FileManagerPackage]
[services.FileManagerPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.PasteboardPackage]
[services.PasteboardPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.StoreReviewPackage]
services = [ "AppInfoPackage", "UserDefaultsPackage" ]
[services.StoreReviewPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.UserDefaultsPackage]
[services.UserDefaultsPackage.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

# Libraries

[libraries.GRDBDatabasePackage]
dependencies = [ "GRDB" ]

[libraries.EquatablePackage]

[libraries.ErrorReportingClientPackage]
skip_tests = true
dependencies = [ "Dependencies", "DependenciesMacros" ]

[libraries.ExtensionsPackage]
dependencies = [ "AsyncAlgorithms", "ConcurrencyExtras" ]
[libraries.ExtensionsPackage.tests]
dependencies = [ "Dependencies" ]

[libraries.FeatureFlagsPackage]

[libraries.SwiftUIExtensionsPackage]
[libraries.SwiftUIExtensionsPackage.tests]
dependencies = [ "SnapshotTesting" ]

[libraries.GRDBDatabaseTestUtilitiesPackage]
skip_tests = true
libraries = [ "GRDBDatabasePackage" ]

[libraries.TestUtilitiesPackage]
skip_tests = true

# Dependency Versions

[shared.refs.Dependencies]
url = "https://github.com/pointfreeco/swift-dependencies.git"
from = "1.2.2"

# Dependencies

[dependencies.AsyncAlgorithms]
url = "https://github.com/apple/swift-async-algorithms.git"
from = "1.0.0"

[dependencies.Dependencies]
dep_ref = "Dependencies"

[dependencies.DependenciesMacros]
dep_ref = "Dependencies"

[dependencies.ConcurrencyExtras]
url = "https://github.com/pointfreeco/swift-concurrency-extras.git"
from = "1.1.0"

[dependencies.GRDB]
url = "https://github.com/groue/GRDB.swift.git"
from = "6.25.0"

[dependencies.Sentry]
url = "https://github.com/getsentry/sentry-cocoa.git"
from = "8.21.0"

[dependencies.SnapshotTesting]
suitable_for_dependents_matching = "\\w+Tests$"
url = "https://github.com/pointfreeco/swift-snapshot-testing.git"
from = "1.16.0"

[dependencies.TelemetryDeck]
url = "https://github.com/TelemetryDeck/SwiftSDK.git"
from = "2.2.1"
