name = "swift-utilities"
tools_version = "5.9"
default_localization = "en"

# Platforms

[platforms.iOS]
supported = [ "\"17.0\"" ]

[platforms.macOS]
supported = [ "\"14.0\"" ]

# Services

[services.FileManager]
[services.FileManager.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

[services.Pasteboard]
[services.Pasteboard.interface]
dependencies = [ "Dependencies", "DependenciesMacros" ]

# Libraries

[libraries.Equatable]

[libraries.Extensions]

[libraries.SwiftUIExtensions]
[libraries.SwiftUIExtensions.tests]
dependencies = [ "SnapshotTesting" ]

[libraries.TestUtilities]
skip_tests = true

# Dependency Versions

[versionRefs.Dependencies]
from = "1.2.2"

# Dependencies

[dependencies.Dependencies]
url = "https://github.com/pointfreeco/swift-dependencies.git"
versionRef = "Dependencies"

[dependencies.DependenciesMacros]
url = "https://github.com/pointfreeco/swift-dependencies.git"
versionRef = "Dependencies"

[dependencies.SnapshotTesting]
suitable_for_dependents_matching = "\\w+Tests$"
url = "https://github.com/pointfreeco/swift-snapshot-testing.git"
from = "1.16.0"
